import * as React from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '../../utils/api';
import { NextPageWithLayout } from '../_app';
import AppLayout from '../../components/AppLayout';
import { useRouter } from 'next/router';

// #fff
// #f9f9f9
// #f3f3f3

const NoteDetailPage: NextPageWithLayout = () => {
    const router = useRouter();
    const [param, setParam] = React.useState('');

    const { data } = api.notes.getOne.useQuery(
        { noteId: param },
        { refetchOnWindowFocus: false, refetchOnReconnect: false }
    );

    // console.log({ data });

    React.useEffect(() => {
        if (router.isReady) {
            setParam(router.query.noteId as string);
        }
    }, [router.isReady]);

    return (
        <>
            <Head>
                <title>QuickNote</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
                    Notes Detail Page: {router.query.noteId}{' '}
                </h1>
            </div>
        </>
    );
};

export default NoteDetailPage;

NoteDetailPage.getLayout = function getLayout(page) {
    return <AppLayout>{page}</AppLayout>;
};
