import Head from 'next/head';
import { NextPage } from 'next';
import Link from 'next/link';

const SignIn: NextPage = () => {
    return (
        <>
            <Head>
                <title>QuickNotes - 404</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex min-h-screen flex-col items-center justify-center bg-white">
                <div className="flex w-1/3 flex-col items-center justify-center gap-12 rounded-md bg-[#f9f9f9] px-4 py-16">
                    <Link href="/" className="text-xl font-bold italic">
                        QuickNote
                    </Link>
                    <p>404: Page Not Found</p>
                </div>
            </main>
        </>
    );
};

export default SignIn;
